name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Upload JARs (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: cozy-plugins
          path: |
            cozy-hub/target/cozy-hub-*.jar
            cozy-holograms/target/cozy-holograms-*.jar
            cozy-npc/target/cozy-npc-*.jar
          if-no-files-found: ignore

      - name: Upload JARs to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            cozy-hub/target/cozy-hub-*.jar
            cozy-holograms/target/cozy-holograms-*.jar
            cozy-npc/target/cozy-npc-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
